# config.yml

backend:
  name: git-gateway
  repo: sssoz/doaj-kit
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'img/uploads'
collections:
  - name: 'building-blocks'
    label: 'building blocks'
    folder: 'building-blocks/'
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "with-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'components'
    label: 'components'
    folder: 'components/'
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "with-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'content-writing'
    label: 'content writing tips'
    folder: 'content-writing/'
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "with-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publishing Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
